batch_size: 1
min_number_images: 20
balanced: 0
paper: 1
aggregation: 'mean'
bag_size: 20
dropout: 0.2
class_weight: 1
oversamplings: 1
img_dim: 128
apply_augmentation: 1
train_ratio: 0.80
test_ratio: 0.20
lr: 3e-7
epochs: 1
paths:
  data_dir: 'data/rbc_images_cleaned'
